### ISSUE TITLE
How can I get MESC PCBA? How much is it? Thank you .

### ISSUE THREAD

**Issue by chrismolony** [davidmolony/MESC_FOC_ESC#14]
How can I get MESC PCBA? How much is it? Thank you .

**Comment by davidmolony** [comment]
The files should (might?) still work with jlcpcb, or you can check out the kicad and regenerate them. It's nearly 3 years since i ordered this and the firmware is now primarily developed on f405rg chips.

The hardware still performs surprisingly well, but there's probably better open source these days. It's mega cheap to produce though!

I paid iirc 150usd for 5x populated boards without capacitors 3 years ago. Can probably get it for similar price now if you use e.g hyg015n10 MOSFETs.

**Comment by StevenShiChina** [comment]
Thanks for your reply. Could you provide the schematic diagram based on the F405rg?  I only found F303CB schematic diagram in your repository.  And what is your e-mail address? or how can I contact you quickly? facebook  or wechat ?

**Comment by davidmolony** [comment]
https://github.com/badgineer/MP2-ESC with
https://github.com/davidmolony/F405_pill

This is the closest to a public f405rg device. Really, MESC became a firmware project supporting loads of different ST MCUs.
https://github.com/davidmolony/MESC_Firmware
